# Generated by Django 4.2.2 on 2023-06-22 03:33

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=15, primary_key=True, serialize=False, verbose_name='Identificador del usuario')),
                ('nombreu', models.CharField(max_length=20, verbose_name='Nombre del usuario')),
                ('apellidou', models.CharField(max_length=20, verbose_name='Apellido del usuario')),
                ('fechanacu', models.DateField(verbose_name='Fecha de nacimiento del usuario')),
                ('correou', models.CharField(max_length=50, unique=True, verbose_name='Correo electronico')),
                ('password', models.CharField(max_length=20, verbose_name='Contraseña del usuario')),
                ('ciudadu', models.CharField(max_length=30, verbose_name='Ciudad del usuario')),
                ('sexou', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('Desc', 'Desconocido'), ('Otro', 'Otro')], max_length=10, verbose_name='Sexo del usuario')),
                ('paisu', django_countries.fields.CountryField(max_length=15, verbose_name='Pais del usuario')),
                ('es_admin', models.BooleanField(default=False)),
                ('u_activo', models.BooleanField(default=True)),
            ],
            options={
                'db_table': '"infousuarios"."usuario"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('act_id', models.AutoField(primary_key=True, serialize=False)),
                ('act_ingreso', models.DateTimeField()),
                ('act_dispositivo', models.CharField(max_length=10)),
                ('act_fin', models.DateTimeField()),
            ],
            options={
                'db_table': '"infousuarios"."actividad"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Beneficio',
            fields=[
                ('benid', models.AutoField(primary_key=True, serialize=False)),
                ('bendescripcion', models.CharField(max_length=50)),
            ],
            options={
                'db_table': '"infousuarios"."beneficio"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Combate',
            fields=[
                ('cmbid', models.AutoField(primary_key=True, serialize=False)),
                ('cmblugar', models.CharField(max_length=20)),
            ],
            options={
                'db_table': '"infopersonajes"."combate"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Jueplataforma',
            fields=[
                ('id_plataforma', models.AutoField(primary_key=True, serialize=False)),
                ('plataforma', models.CharField(max_length=20)),
            ],
            options={
                'db_table': '"infopersonajes"."jueplataforma"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Medio',
            fields=[
                ('medio_id', models.AutoField(primary_key=True, serialize=False)),
                ('medfecestreno', models.DateField()),
                ('medcomcreacion', models.CharField(max_length=20)),
                ('medcomproduc', models.CharField(max_length=40)),
                ('medrating', models.IntegerField(choices=[(1, '1-Mala'), (2, '2-Mediocre'), (3, '3-Regular'), (4, '4-Buena'), (5, '5-Excelente')])),
                ('medsinopsis', models.CharField(max_length=120)),
            ],
            options={
                'db_table': 'medio',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Objeto',
            fields=[
                ('obid', models.AutoField(primary_key=True, serialize=False)),
                ('objnombre', models.CharField(max_length=20)),
                ('objmaterial', models.CharField(max_length=20)),
                ('objdescripcion', models.CharField(max_length=70)),
            ],
            options={
                'db_table': '"infopersonajes"."objeto"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Organizacion',
            fields=[
                ('id_organizacion', models.AutoField(primary_key=True, serialize=False)),
                ('org_nombre', models.CharField(max_length=40)),
                ('eslogan', models.CharField(max_length=100)),
                ('tipo_organizacion', models.CharField(choices=[('Malvada', 'Malvada'), ('Civil', 'Civil'), ('Heroica', 'Heroica')])),
                ('comic_primer_vez', models.CharField(max_length=30)),
                ('objetivo_principal', models.CharField(max_length=70)),
                ('lugar_creacion', models.CharField(max_length=20)),
            ],
            options={
                'db_table': '"infopersonajes"."organizacion"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('per_id', models.AutoField(primary_key=True, serialize=False)),
                ('idioma', models.CharField(max_length=10)),
                ('percorreo', models.CharField()),
            ],
            options={
                'db_table': '"infousuarios"."perfil"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Personaje',
            fields=[
                ('personaje_id', models.AutoField(primary_key=True, serialize=False)),
                ('genc', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('Desc', 'Desconocido'), ('Otro', 'Otro')], verbose_name='Sexo del personaje')),
                ('primer_nombre', models.CharField(max_length=20, verbose_name='Primer nombre del personaje')),
                ('segundo_nombre', models.CharField(blank=True, max_length=20, null=True, verbose_name='Segundo nombre del personaje')),
                ('primer_apellido', models.CharField(max_length=20, verbose_name='Primer apellido del personaje')),
                ('segundo_apellido', models.CharField(blank=True, max_length=20, null=True, verbose_name='Segundo apellido del personaje')),
                ('color_pelo', models.CharField(max_length=15, verbose_name='Color del pelo del personaje')),
                ('color_ojos', models.CharField(max_length=15, verbose_name='Color de los ojos del personaje')),
                ('frase_celebre', models.CharField(blank=True, max_length=75, null=True, verbose_name='Frase más celebre del personaje')),
                ('comic_primer_vez', models.CharField(max_length=50, verbose_name='Primera aparición en comics del personaje')),
                ('estadomarital', models.CharField(choices=[('Casado', 'Casado'), ('Soltero', 'Soltero'), ('Viudo', 'Viudo'), ('Divorciado', 'Divorciado')], verbose_name='Estado Marital del personaje')),
            ],
            options={
                'db_table': '"infopersonajes"."personaje"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Poder',
            fields=[
                ('podid', models.AutoField(primary_key=True, serialize=False)),
                ('ponombre', models.CharField(max_length=30)),
                ('podescripcion', models.CharField(max_length=70)),
                ('ponaturaleza', models.CharField(max_length=20)),
            ],
            options={
                'db_table': '"infopersonajes"."poder"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sede',
            fields=[
                ('id_sede', models.AutoField(primary_key=True, serialize=False)),
                ('sede_nombre', models.CharField(max_length=20)),
                ('sede_ubicacion', models.CharField(max_length=20)),
                ('tipo_edificacion', models.CharField(choices=[('Subterranea', 'Subterranea'), ('voladora', 'voladora'), ('Superficial', 'Superficial')])),
            ],
            options={
                'db_table': '"infopersonajes"."sede"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Suscripcion',
            fields=[
                ('susid', models.AutoField(primary_key=True, serialize=False)),
                ('sustipo', models.CharField(max_length=10)),
                ('susdescripcion', models.CharField(max_length=50)),
                ('sustarifa', models.DecimalField(decimal_places=4, max_digits=5)),
            ],
            options={
                'db_table': '"infousuarios"."suscripcion"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tarjetacredito',
            fields=[
                ('tdcnumero', models.BigIntegerField(primary_key=True, serialize=False, verbose_name='Numero de la tarjeta')),
                ('tdcfecvencimiento', models.DateField(verbose_name='Fecha de vencimiento de la tarjeta')),
                ('tdccvv', models.IntegerField(validators=[django.core.validators.MaxValueValidator(999), django.core.validators.MinValueValidator(100)], verbose_name='Codigo de seguridad de la tarjeta')),
            ],
            options={
                'db_table': '"infousuarios"."tarjetacredito"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tipoobj',
            fields=[
                ('idtipo', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_nombre', models.CharField(max_length=20)),
                ('tipo_descripcion', models.CharField(max_length=70)),
            ],
            options={
                'db_table': '"infopersonajes"."tipoobj"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Civil',
            fields=[
                ('personaje', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='appone.personaje')),
            ],
            options={
                'db_table': '"infopersonajes"."civil"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Creador',
            fields=[
                ('personaje_id_cre', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='appone.personaje')),
                ('id_creador', models.IntegerField()),
                ('creador_nombre', models.CharField(max_length=20)),
                ('creador_apellido', models.CharField(max_length=20)),
            ],
            options={
                'db_table': '"infopersonajes"."creador"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Heroe',
            fields=[
                ('personaje', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='appone.personaje')),
                ('nombre_superheroe', models.CharField(max_length=20)),
                ('color_traje', models.CharField(max_length=15)),
                ('logotipo', models.CharField(max_length=75)),
            ],
            options={
                'db_table': '"infopersonajes"."heroe"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HistoricoMatrimonio',
            fields=[
                ('id_pers_conyug1', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='appone.personaje')),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': '"infopersonajes"."historico_matrimonio"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HistoricoPersonaje',
            fields=[
                ('fk_pers_org', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='appone.personaje')),
                ('fundador', models.BooleanField()),
                ('lider', models.BooleanField()),
                ('fecha_union', models.DateField()),
                ('fecha_salida', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': '"infopersonajes"."historico_personaje"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Juego',
            fields=[
                ('medio', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='appone.medio')),
                ('medtipo', models.CharField(choices=[('accion', 'accion'), ('aventura', 'aventura'), ('estrategia', 'estrategia'), ('rpg', 'rpg'), ('mundo abierto', 'mundo abierto'), ('simulacion', 'simulacion')])),
                ('juegocompania', models.CharField(max_length=20)),
            ],
            options={
                'db_table': '"infopersonajes"."juego"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Nacionalidad',
            fields=[
                ('personaje_id_nac', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='appone.personaje')),
                ('id_nacion', models.IntegerField()),
                ('nacion_nombre', models.CharField(max_length=20)),
                ('nacion_continente', models.CharField(choices=[('America', 'America'), ('Europa', 'Europa'), ('Africa', 'Africa'), ('Asia', 'Asia'), ('Oceania', 'Oceania')])),
            ],
            options={
                'db_table': '"infopersonajes"."nacionalidad"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ocupacion',
            fields=[
                ('personaje_id_ocu', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='appone.personaje')),
                ('id_ocupacion', models.IntegerField()),
                ('ocupa_nombre', models.CharField(max_length=20)),
            ],
            options={
                'db_table': '"infopersonajes"."ocupacion"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OrganizacionMedio',
            fields=[
                ('fk_med_org', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='appone.medio')),
                ('estado', models.CharField(max_length=20)),
            ],
            options={
                'db_table': '"infopersonajes"."organizacion_medio"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pelicula',
            fields=[
                ('medio', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='appone.medio')),
                ('medtipo', models.CharField(choices=[('animada', 'animada'), ('liveaction', 'liveaction'), ('stopmotion', 'stopmotion')])),
                ('peldirector', models.CharField(max_length=40)),
                ('pelduracion', models.IntegerField()),
                ('pelcosteprod', models.DecimalField(decimal_places=4, max_digits=5)),
                ('pelganancias', models.DecimalField(decimal_places=4, max_digits=5)),
            ],
            options={
                'db_table': '"infopersonajes"."pelicula"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PerfilMedio',
            fields=[
                ('fk_perf_med', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='appone.perfil')),
                ('calificacion', models.IntegerField()),
                ('fecha_vista', models.DateTimeField()),
            ],
            options={
                'db_table': '"infousuarios"."perfil_medio"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PersonajeMedio',
            fields=[
                ('fk_med_pers', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='appone.medio')),
                ('actor_tipo', models.CharField()),
                ('actor_nombre', models.CharField(max_length=40)),
                ('personaje_tipo', models.CharField(choices=[('Antagonista', 'Antagonista'), ('Protagonista', 'Protagonista'), ('Secundario', 'Secundario')])),
            ],
            options={
                'db_table': '"infopersonajes"."personaje_medio"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PersonajeObjeto',
            fields=[
                ('fk_obj_pers', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='appone.objeto')),
                ('hereditario', models.BooleanField()),
            ],
            options={
                'db_table': '"infopersonajes"."personaje_objeto"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PersonajePoder',
            fields=[
                ('fk_pod_pers', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='appone.poder')),
                ('hereditario', models.BooleanField()),
            ],
            options={
                'db_table': '"infopersonajes"."personaje_poder"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RegistroCombates',
            fields=[
                ('fk_cmb_reg', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='appone.combate')),
                ('cmbfecha', models.DateField()),
            ],
            options={
                'db_table': '"infopersonajes"."registro_combates"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Serie',
            fields=[
                ('medio', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='appone.medio')),
                ('medtipo', models.CharField(choices=[('animada', 'animada'), ('liveaction', 'liveaction'), ('stopmotion', 'stopmotion')])),
                ('sercreador', models.CharField(max_length=40)),
                ('serepisodios', models.IntegerField()),
                ('sercanal', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'serie',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SuscripcionBeneficio',
            fields=[
                ('fk_ben_sus', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='appone.beneficio')),
            ],
            options={
                'db_table': '"infousuarios"."suscripcion_beneficio"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Villano',
            fields=[
                ('personaje', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='appone.personaje')),
                ('nombre_supervillano', models.CharField(max_length=20)),
                ('objetivo', models.CharField(max_length=50)),
            ],
            options={
                'db_table': '"infopersonajes"."villano"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Amistad',
            fields=[
                ('id_civil', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='appone.civil')),
            ],
            options={
                'db_table': '"infopersonajes"."amistad"',
                'managed': False,
            },
        ),
    ]
